### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by Jennifer-6** [chenxy99/ANOC#4]
Can you give me the characteristics of training directly?

**Comment by chenxy99** [comment]
Hello, thanks for your interest in our work. The saliency feature is from the [Download the extra nocaps dataset that is not provided by nocaps and unzip it](https://github.com/chenxy99/ANOC#datasets). Hope this can help you.

Best regard

**Comment by Jennifer-6** [comment]
hello,I have downloaded all of feature. There is a problem. When loading the coco_train2017_penultimate_feature, in code occur ['attention_maps'] ,but the penultimate_feature H5 file I downloaded,the key values in H5 only have the attributes ['height'], ['image_id '], ['penultimate_features'], the['penultimate_ Feature'] and ['attention_maps'] are same thing? or is wrong the H5 file I downloaded. Another question, can I have the trained model?
Looking forward to your reply~







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenxy99/ANOC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 下午2:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenxy99/ANOC] feature (Issue #4)





 
Hello, thanks for your interest in our work. The saliency feature is from the Download the extra nocaps dataset that is not provided by nocaps and unzip it. Hope this can help you.
 
Best regard
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenxy99** [comment]
['penultimate_ Feature'] is the penultimate feature map, the shape may be H*W*512, while ['attention_maps'] is the saliency prediction of an image, the shape may be H*W*1. 

I will update the readme file for the trained model when I finish the travel.

Best

**Comment by chenxy99** [comment]
Hello,

I just update the code, you can try it again.

Best regards
