### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by Jennifer-6** [chenxy99/ANOC#5]
![image](https://user-images.githubusercontent.com/61728321/147573915-e269d2f8-9ca8-465e-b4b8-1572d8638d01.png)
"data/nocaps_data/penultimate_features_mean/coco/coco_train2017_penultimate_features.h5"this feature has no attribute of['attention_maps'].
Can you tell me the time and GPU memory required for this network training

**Comment by chenxy99** [comment]
Hello,

attention_map may not be used in the implementation. Since I try several versions of the code and I may upload another implementation. I will check it when I finish my travel. 

For CE loss training, it costs ~12 hours for one 2080ti (12G), while for SCST, it costs ~24 hours for one 2080ti.
