### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by Jennifer-6** [chenxy99/ANOC#7]
![f051041720b48a384764e9497d90a4e](https://user-images.githubusercontent.com/61728321/153712690-2258f667-e3d4-435f-b3f6-46212fccdcee.png)
I have encountered this problem. The maximum number of files opened  is 2048. Do l need  set it to 4500 (the amount of validation set data)? Why are there such problems here?

**Comment by chenxy99** [comment]
Hello,

I just meet this problem 2 years ago and I raise the issue for the author of the baseline https://github.com/nocaps-org/updown-baseline/issues/9. But they cannot fully address my problem. And after two weeks, I find the evalai can work well for me.  It is so strange. But you can follow their suggestion that you can submit the json manually.

Best
