### ISSUE TITLE
How to visualize human attention?

### ISSUE THREAD

**Issue by Jennifer-6** [chenxy99/ANOC#8]
Thank you very much for your reply and help. How to visualize  salience maps ? I noticed that the human attention in the program is a 512 dimensional feature. Can you give me the original features proposed from the SAM network without global average pooling.thanks a lot~

**Comment by chenxy99** [comment]
The salience map is a 30 x 40 map. I update the readme, you can check it.

**Comment by chenxy99** [comment]
The original 512-dimensional feature is too large since the size of it is 120k x 512 x 30 x 40. It takes a lot of space. I remember it will take up 100Gb space.
